services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: python main.py ${MODEL_VERSION}
    networks:
      - external

networks:
  external:
    external: true
